# Generated by Django 3.0.2 on 2020-01-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='sid',
            field=models.CharField(blank=True, default='SHYGNFSOK', max_length=10, unique=True),
        ),
    ]
