# Generated by Django 3.0.2 on 2020-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200110_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='sid',
            field=models.CharField(blank=True, default='S1Y8XPYCW', max_length=10, unique=True),
        ),
    ]
