# Generated by Django 3.0.2 on 2020-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200110_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='sid',
            field=models.CharField(blank=True, default='SLSHMUAYM', max_length=10, unique=True),
        ),
    ]
