# Generated by Django 3.0.2 on 2020-01-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20200110_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='pin',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='sid',
            field=models.CharField(blank=True, default='SMU96PPSC', max_length=10, unique=True),
        ),
    ]
