# Generated by Django 3.0.2 on 2020-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20200111_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='pin',
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='sid',
            field=models.CharField(blank=True, default='SERTHNAKT', max_length=10, unique=True),
        ),
    ]
