# Generated by Django 3.0.2 on 2020-01-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyerProfile',
        ),
    ]
