# Generated by Django 3.0.2 on 2020-01-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_buyerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='brcwifje', max_length=10, unique=True),
        ),
    ]
