# Generated by Django 3.0.2 on 2020-01-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20200110_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='8H00EBGE', max_length=10, unique=True),
        ),
    ]
