# Generated by Django 3.0.2 on 2020-01-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_auto_20200110_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='BOIUBXVAQ', max_length=10, unique=True),
        ),
    ]
