# Generated by Django 3.0.2 on 2020-01-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_auto_20200110_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='BBG84I9S2', max_length=10, unique=True),
        ),
    ]
