# Generated by Django 3.0.2 on 2020-01-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20200110_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='BUEDPW7I7', max_length=10, unique=True),
        ),
    ]
