# Generated by Django 3.0.2 on 2020-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_auto_20200110_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='is_buyer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='B40X7PKB0', max_length=10, unique=True),
        ),
    ]
