# Generated by Django 3.0.2 on 2020-01-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_auto_20200110_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='B0URTOYG2', max_length=10, unique=True),
        ),
    ]
