# Generated by Django 3.0.2 on 2020-01-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0011_auto_20200110_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='commodity',
            field=models.CharField(default='crop', max_length=30),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='district',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='pin',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='BMWYLQGKY', max_length=10, unique=True),
        ),
    ]
