# Generated by Django 3.0.2 on 2020-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_auto_20200111_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='bid',
            field=models.CharField(blank=True, default='BH1AYJ1LH', max_length=10, unique=True),
        ),
    ]
